class_name UIConstants

const POSITIONS = {
	"HOTBAR_TOP_MARGIN": 4.0,
	"INVENTORY_CENTER_OFFSET": Vector2.ZERO
}

const ANIMATIONS = {
	"SLIDE_DURATION": 0.4,
	"FADE_DURATION": 0.3
}

const SLOT_CONFIGS = {
	"DEFAULT_SIZE": Vector2(64, 64),
	"HOTBAR_SIZE": Vector2(64, 64)
}
